### ISSUE TITLE
No keybinding support for linux add/remove bookmark (Cmd+F2)

### ISSUE THREAD

**Issue by tecfu** [atom/bookmarks#26]
Linux does not have a cmd key, and Ctrl+F2 does not work.

**Comment by izuzak** [comment]
@tecfu Which version of Atom are you using and which OS exactly? What do you see in the [keybinding resolver](https://atom.io/docs/latest/hacking-atom-debugging#check-the-keybindings) when you press `ctrl-f2`?

Also, the add/remove bookmark is not bound to `ctrl-f2` on linux, it's bound to `ctrl-shift-f2`:

https://github.com/atom/bookmarks/blob/410b225453318c30481d12bf1ae243e292a1047a/keymaps/bookmarks.cson#L15

**Comment by tecfu** [comment]
Thanks for addressing this!

I'm running Ubuntu 14.04 with XFCE as the desktop environment (Xubuntu). My conflict arises from xfwm4 version 4.11.1.

The default keybinding ctrl+F2 in the Atom bookmarks plugin conflicts with the default keybinding of ctrl+F2 in xfwm - which is the window manager for the Xfce desktop environment.

See:
----
https://packages.debian.org/wheezy/xfce/xfwm4
https://wiki.archlinux.org/index.php/Xfwm

ctrl+F2 in xfwm switches the user to "Workspace 2" in xfxe.

It can, of course, be remapped in the window manager configuration, but I'll propose ctrl+alt+F2 instead. 

Here's the link to my pull request for that change.

https://github.com/atom/bookmarks/pull/27

**Comment by izuzak** [comment]
@tecfu Thanks for those details. Does this needs to be changed for all Atom users on Linux or could you also change this locally if it's a problem on your setup? See:

https://atom.io/docs/latest/using-atom-basic-customization#customizing-key-bindings
https://atom.io/docs/latest/behind-atom-keymaps-in-depth

Would that approach work for you? Or will everyone using Linux have the same problem as you are?

**Comment by tecfu** [comment]
I think it is safe to guess that ctrl+F2 probably maps to "Workspace 2" at least half of all linux desktop systems by default.  

While we could all remap our deskop keybindings to suit Atom, I think conflict isn't quite intuitive and would lead to a lot of linux users getting frustrated and abandoning the feature - or wasting time trying to find this bug. 

So I'd like to see you patch it.

**Comment by izuzak** [comment]
@tecfu I was just asking as someone who doesn't use Linux -- it's helpful to provide as many details as possible when describing such problems, as I'm sure you'd agree. Knowing whether this affects 1 user or all users helps when making decisions. Does that make sense?

**Comment by tecfu** [comment]
Understood, thanks again for looking at this.
