### ISSUE TITLE
Center bookmarks vertically on jump

### ISSUE THREAD

**Issue by doggan** [atom/bookmarks#32]
When cycling through bookmarks, especially in really long files, bookmark jumping feels jarring.

Sometimes a bookmark will be in the top section of the view window, and sometimes towards the bottom.  For example, when the bookmark cycling wraps around to the first bookmark in the file, the bookmark will be on the top of the view. When you cycle to the next bookmark towards the bottom of the file, the bookmark will be on the bottom of the view. This also will occur if using 'next bookmark' followed by 'previous bookmark' when the bookmarks are not within the same view.

It would be a nice option to be able to enable a 'center bookmark on jump' option, which will scroll the view so that the bookmark is in the center (vertical) of the window if possible. This would provide some consistency to bookmark positions when cycling through long files with many bookmarks. If the bookmarks are already within the same view prior to the jump, the view positioning should not change (which is how it is currently).

**Comment by acontreras89** [comment]
:+1: 
Although I personally think this should be the default behavior, not an option. Either aligning bookmarks to the center of the screen or to the top; any way that is consistent would be ok in my opinion.

**Comment by bluexnine** [comment]
This would be a good enhancement to have.

**Comment by bwiggs** [comment]
+1 for this!

**Comment by acontreras89** [comment]
lovely! Thanks @Tyriar!

**Comment by Tyriar** [comment]
Glad to see it land :)

**Comment by lee-dohm** [comment]
This is in the current version of `master`, which means that it is slated to progress along the v1.6.0 track.
