### ISSUE TITLE
Going to a bookmark from View All should search in all panes

### ISSUE THREAD

**Issue by acontreras89** [atom/bookmarks#35]
When using `Bookmarks: View All`, the key-binding `enter` (or `shift-enter` as `fuzzy-finder` does) should look for the item in all panes instead of opening it in the active one.

**Comment by acontreras89** [comment]
Just created atom/bookmarks#36 to add this enhancement.

**Comment by mliq** [comment]
Clicking a bookmark in another tab does not navigate there - is this a regression?

**Comment by solendil** [comment]
I confirm clicking a bookmark does not navigate there.

**Comment by Ben3eeE** [comment]
Closing this since it looks like it was fixed by #36 and again by #65
