### ISSUE TITLE
Unable to change keymaps

### ISSUE THREAD

**Issue by iherman** [atom/bookmarks#49]
I tried to change the keymap for bookmarks; the default (using F2) interferes with some general OSX operation. I have added the followings to my ``keymap.cson`` file

```
'atom-workspace, atom-workspace atom-text-editor':
  'cmd-f1' : 'bookmarks:toogle-bookmark'
  'cmd-f2' : 'bookmarks:jump-to-text-bookmark'
  'cmd-f3' : 'bookmarks:jump-to-previous-bookmark'

'atom-workspace':
  'cmd-f1' : 'bookmarks:toogle-bookmark'
  'cmd-f2' : 'bookmarks:jump-to-text-bookmark'
  'cmd-f3' : 'bookmarks:jump-to-previous-bookmark'
```

But it seems to have no effect. Note that I have another, similar entry for another package (markdown) in the same file and that works, ie, the settings are properly read by Atom

**Comment by lee-dohm** [comment]
Here's what worked for me:

```coffee
'atom-text-editor':
  'cmd-f1': 'bookmarks:toggle-bookmark'
'.platform-darwin atom-text-editor':
  'cmd-f2' : 'bookmarks:jump-to-text-bookmark'
  'cmd-f3' : 'bookmarks:jump-to-previous-bookmark'
```

It is generally best to start from the [keymap built in to the package](https://github.com/atom/bookmarks/blob/master/keymaps/bookmarks.cson) and go from there. Once I did that, I used the Keybinding Resolver (<kbd>Cmd+.</kbd> on OS X and <kbd>Ctrl+.</kbd> on other platforms) to debug things.

I hope that helps and let us know if you run into any more problems!
