### ISSUE TITLE
When save a file bookmark is removed

### ISSUE THREAD

**Issue by guilhermepatriarca** [atom/bookmarks#56]
When save a file bookmark is removed.
![error](https://cloud.githubusercontent.com/assets/14976020/15179989/de9cef74-1776-11e6-8d8b-0cd90fa7ca07.gif)

**Comment by 50Wliu** [comment]
@guilhermepatriarca Sorry for the late reply - can you reproduce this in safe mode (`atom --safe`)?

**Comment by guilhermepatriarca** [comment]
Yes in safe mode Work

**Comment by 50Wliu** [comment]
Ok, that means one of your packages is causing this problem.  You can try using the [package-cop](https://atom.io/packages/package-cop) package to figure out which one it is.

**Comment by rainbowtiger** [comment]
I tried package cop, turned off ALL packages, then tested, and bookmarks still get get lost after saving. Package cop says the package "Atom" is the cause.

**Comment by 50Wliu** [comment]
@rainbowtiger please open a new issue and we'll investigate.
