### ISSUE TITLE
Bookmark not surviving atom restart

### ISSUE THREAD

**Issue by pjvalla** [atom/bookmarks#68]
Bookmark is not surviving project restart.
1. Open project from project root directory
   `atom .`
2. Add bookmark to file within project.
3. Shutdown atom
4. Reopen project
   `atom .`

Bookmarks are gone.  I am on Ubuntu 14.04, running atom 1.8.0.  
I am also noticing that the bookmarks are not highlighted in minimap-bookmarks, even though I can cycle through them and see the blue bookmark symbol on the left.

I am not closing the file before shutting down atom.  It was my impression that the bookmarks should be serialized on shutdown and are associated with an atom project.

**Comment by jessejanderson** [comment]
☝️ same

**Comment by SavageCore** [comment]
+1 On windows

From project root:

1. `atom --safe .`
2. Add bookmark to file within project.
3. Close atom.
4. `atom --safe .`

**Comment by pjvalla** [comment]
@SavageCore I followed your procedure and the bookmarks still do not survive.

**Comment by SavageCore** [comment]
@pjvalla Yes that is correct, I posted as `--safe` (safe mode) proves no third party package causes this bug. [Previously](https://github.com/atom/bookmarks/issues/22#issuecomment-65286373) this has been caused by other packages.

**Comment by pjvalla** [comment]
Okay, thanks for clarifying.

**Comment by skleinbo** [comment]
Same here, running `Atom 1.10.0` with `Bookmarks 0.41.0` on Mac OSX El Capitan.

**Comment by pmgouveia** [comment]
found this package: https://atom.io/packages/nav-panel-plus much better! ^^

**Comment by PixelT** [comment]
+1

**Comment by mateuspv** [comment]
FYI: I've tried to reproduce this on Window running `atom . --safe`, but I could **not** produce.
Windows:
Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Comment by rsese** [comment]
I just tried this on Windows 10 with Atom 1.21.1 and wasn't able to reproduce - after restart, the bookmark I added was still there.  I also tried on macOS 10.12.6 off of master and couldn't reproduce there either.  Going to go ahead and close but if folks can still reproduce let me know.
