### ISSUE TITLE
Bookmarks invisible

### ISSUE THREAD

**Issue by cortner** [atom/bookmarks#79]
For the past 2-3 updates, my bookmarks have become invisible. I can set them and jump between them, but they are not shown next to the line numbers.

This is on Mac OS X, and I've tested it with several UIs and syntax theme combinations.

**Comment by Ben3eeE** [comment]
Sounds like you have manually installed bookmarks. Please run `apm uninstall bookmarks` and use the version that is bundled with atom which should fix this problem.

**Comment by cortner** [comment]
thank you - that was indeed the issue. sorry for the noise.
