### ISSUE TITLE
Bookmarks and folding with hidden line numbers

### ISSUE THREAD

**Issue by svoop** [atom/bookmarks#8]
First column features such as bookmarks and folding should be available when line numbers are hidden.

**Comment by mateuspv** [comment]
Hi all, I was review this issue and it's seems fixed:
![line-number-with-bokmark](https://user-images.githubusercontent.com/4995440/31521493-15ae636a-af80-11e7-8564-6ab49f660e55.png)
@probablycorey Can we close it ?

**Comment by svoop** [comment]
Line folding now works when line numbers are disabled. Thanks a bunch for implementing this and for the extra centimeter of editor space :smile:
