### ISSUE TITLE
Bookmark should remember column, text selection

### ISSUE THREAD

**Issue by blalor** [atom/bookmarks#9]
I'm coming to Atom from Sublime Text 2.  In ST2, creating a bookmark also captures selected text and cursor position on the line.  When you go to the bookmark, the previously-selected text (if any) is selected again, and the column position is restored.  This would be a nice feature to have in Atom, as well.

**Comment by benogle** [comment]
This might not be terribly hard to implement. Currently it just creates a marker on the beginning of the line as the bookmark marker. It could cop the range of the current selection for the bookmark marker. Though, there might be undesirable behavior when the bookmarked line is changed, or the selection bookmarked is changed.

**Comment by Tyriar** [comment]
Some more info on how this is handled in Sublime; it seems to keep track of the start and end positions of the text, probably by listening to any edit events on that line and updating the bookmark when necessary.

For example if a line has the text `"abc def ghi"` and `"def"` is the bookmark's selected text, you could modify the text like this:

1. Add `1` before `d` (increment bookmark start and end)
2. Add `2` after `d` (increment bookmark end)
3. Add `3` before `f` (increment bookmark end
4. Add `4` after `f` (no bookmark change required)

So the string is now `"abc 1d2e3f4 ghi"` and the bookmark selected text becomes `"d2e3f``.

**Comment by Tyriar** [comment]
Looks like the above is what a `Marker` does.
